"use client";

import Head from "next/head";
import { useState } from "react";
import { ISingleAuestionAndAnswer } from "@/types/common";
import { IChatResponse, IMessage } from "@/types/openai";

export default function Home() {
  // are you in the process of answering
  const [loading, setLoading] = useState(false);
  // input box content
  const [input, setInput] = useState("");
  // current answer
  const [answer, setAnswer] = useState<string>("");
  // historical Q&A content
  const [history, setHistory] = useState<ISingleAuestionAndAnswer[]>([]);
  // set the message object of OpenAi
  const [messages, setMessages] = useState<(IMessage | IChatResponse)[]>([]);

  const generateResponse = async (e: React.MouseEvent<HTMLButtonElement>) => {
    const tempQuestion = `${input} Generate a response with less than 200 characters.`;
    let tempAnswer = "";

    e.preventDefault();
    setLoading(true);

    const response = await fetch("/api/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt: tempQuestion,
      }),
    });

    if (!response.ok) {
      throw new Error(response.statusText);
    }

    const data = response.body;
    if (!data) {
      return;
    }

    const reader = data.getReader();
    const decoder = new TextDecoder();
    let done = false;

    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      tempAnswer = tempAnswer + decoder.decode(value);
      setAnswer(tempAnswer);
    }

    setHistory([
      ...history,
      {
        question: tempQuestion,
        answer: tempAnswer,
      },
    ]);
    setInput("");
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>ChatGPT Mini App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to my app</h1>
        <div>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            rows={4}
            maxLength={200}
            placeholder={"e.g. What is React?"}
          />
          {!loading ? (
            <button onClick={(e) => generateResponse(e)}>
              Generate Response &rarr;
            </button>
          ) : (
            <button disabled>
              <div>...</div>
            </button>
          )}
          {answer && <div>{answer}</div>}
          <div>=============</div>
          {history.map((item) => (
            <div key={item.question}>
              <div>{item.question}</div>
              <div>{item.answer}</div>
              <div>---------------------------------</div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
