import Head from "next/head";
import styles from "@/styles/Home.module.css";

function SendMsg() {
  const handlerClick = async () => {
    try {
      const res = await fetch(`/api/chat`, {
        method: "POST",
      });
      const data = await res.json();
      console.log(data);
    } catch (err) {
      console.log(err);
    }
  };
  return <button onClick={handlerClick}>I'm a button</button>;
}

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatGPT Mini App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to my app</h1>
        <SendMsg />
      </main>
    </>
  );
}
